// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (
    id,
    user_id,
    status
)
VALUES ($1, $2, 'active')
RETURNING id, user_id, status, created_at, updated_at
`

type CreateCartParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.ID, arg.UserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItemsByCartID = `-- name: DeleteCartItemsByCartID :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) DeleteCartItemsByCartID(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCartItemsByCartID, cartID)
	return err
}

const getActiveCartByUser = `-- name: GetActiveCartByUser :one
SELECT id, user_id, status, created_at, updated_at
FROM carts
WHERE user_id = $1
AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveCartByUser(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartByUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemQuantity = `-- name: GetCartItemQuantity :one
SELECT quantity
FROM cart_items
WHERE cart_id = $1
  AND product_id = $2
LIMIT 1
`

type GetCartItemQuantityParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) GetCartItemQuantity(ctx context.Context, arg GetCartItemQuantityParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCartItemQuantity, arg.CartID, arg.ProductID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getCartItemsWithProductStock = `-- name: GetCartItemsWithProductStock :many
SELECT
    ci.product_id,
    p.name,
    p.price,
    ci.quantity,
    p.is_available,
    p.kitchen_quantity
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
ORDER BY p.name
`

type GetCartItemsWithProductStockRow struct {
	ProductID       uuid.UUID `json:"product_id"`
	Name            string    `json:"name"`
	Price           string    `json:"price"`
	Quantity        int32     `json:"quantity"`
	IsAvailable     bool      `json:"is_available"`
	KitchenQuantity int32     `json:"kitchen_quantity"`
}

func (q *Queries) GetCartItemsWithProductStock(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductStockRow, error) {
	rows, err := q.db.QueryContext(ctx, getCartItemsWithProductStock, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsWithProductStockRow
	for rows.Next() {
		var i GetCartItemsWithProductStockRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.IsAvailable,
			&i.KitchenQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItemsWithProducts = `-- name: GetCartItemsWithProducts :many
SELECT ci.product_id, p.name, p.price, ci.quantity
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.cart_id = $1
ORDER BY p.name
`

type GetCartItemsWithProductsRow struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Price     string    `json:"price"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) GetCartItemsWithProducts(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCartItemsWithProducts, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsWithProductsRow
	for rows.Next() {
		var i GetCartItemsWithProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :execrows
DELETE FROM cart_items
WHERE cart_id = $1
  AND product_id = $2
`

type RemoveCartItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeCartItem, arg.CartID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (
    id,
    cart_id,
    product_id,
    quantity
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id) 
DO UPDATE SET
    quantity = cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, quantity, created_at
`

type UpsertCartItemParams struct {
	ID        uuid.UUID `json:"id"`
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, upsertCartItem,
		arg.ID,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
