// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const decreaseProductKitchenQuantity = `-- name: DecreaseProductKitchenQuantity :execrows
UPDATE products
SET
    kitchen_quantity = kitchen_quantity - $2,
    is_available = (kitchen_quantity - $2) > 0,
    updated_at = now()
WHERE id = $1
  AND is_available = true
  AND kitchen_quantity >= $2
`

type DecreaseProductKitchenQuantityParams struct {
	ID              uuid.UUID `json:"id"`
	KitchenQuantity int32     `json:"kitchen_quantity"`
}

func (q *Queries) DecreaseProductKitchenQuantity(ctx context.Context, arg DecreaseProductKitchenQuantityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decreaseProductKitchenQuantity, arg.ID, arg.KitchenQuantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id,
    restaurant_id,
    name,
    description,
    price,
    is_available,
    kitchen_quantity,
    created_at,
    updated_at,
    external_id,
    image_url
FROM products
WHERE id = $1
LIMIT 1
`

type GetProductByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	RestaurantID    uuid.UUID      `json:"restaurant_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	IsAvailable     bool           `json:"is_available"`
	KitchenQuantity int32          `json:"kitchen_quantity"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ExternalID      sql.NullInt32  `json:"external_id"`
	ImageUrl        sql.NullString `json:"image_url"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.KitchenQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ImageUrl,
	)
	return i, err
}

const listProductsByRestaurant = `-- name: ListProductsByRestaurant :many
SELECT 
    id,
    external_id,
    restaurant_id,
    name,
    description,
    price,
    image_url,
    is_available,
    created_at,
    updated_at
FROM products
WHERE restaurant_id = $1
ORDER BY name
`

type ListProductsByRestaurantRow struct {
	ID           uuid.UUID      `json:"id"`
	ExternalID   sql.NullInt32  `json:"external_id"`
	RestaurantID uuid.UUID      `json:"restaurant_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsAvailable  bool           `json:"is_available"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) ListProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]ListProductsByRestaurantRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByRestaurantRow
	for rows.Next() {
		var i ListProductsByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.RestaurantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (
    id,
    restaurant_id,
    external_id,
    name,
    description,
    price,
    is_available,
    image_url,
    kitchen_quantity,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (external_id) DO UPDATE SET
    restaurant_id = EXCLUDED.restaurant_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    is_available = EXCLUDED.is_available,
    image_url = EXCLUDED.image_url,
    updated_at = now()
`

type UpsertProductParams struct {
	ID              uuid.UUID      `json:"id"`
	RestaurantID    uuid.UUID      `json:"restaurant_id"`
	ExternalID      sql.NullInt32  `json:"external_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Price           string         `json:"price"`
	IsAvailable     bool           `json:"is_available"`
	ImageUrl        sql.NullString `json:"image_url"`
	KitchenQuantity int32          `json:"kitchen_quantity"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.ExecContext(ctx, upsertProduct,
		arg.ID,
		arg.RestaurantID,
		arg.ExternalID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsAvailable,
		arg.ImageUrl,
		arg.KitchenQuantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
