// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DecreaseProductKitchenQuantity(ctx context.Context, arg DecreaseProductKitchenQuantityParams) (int64, error)
	DeleteCartItemsByCartID(ctx context.Context, cartID uuid.UUID) error
	GetActiveCartByUser(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetCartItemQuantity(ctx context.Context, arg GetCartItemQuantityParams) (int32, error)
	GetCartItemsWithProductStock(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductStockRow, error)
	GetCartItemsWithProducts(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsWithProductsRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetRestaurantByExternalID(ctx context.Context, externalid int32) (Restaurant, error)
	GetRestaurantWithProducts(ctx context.Context, restaurantid uuid.UUID) ([]GetRestaurantWithProductsRow, error)
	GetRestaurants(ctx context.Context) ([]GetRestaurantsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error)
	ListProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]ListProductsByRestaurantRow, error)
	ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]ListRestaurantsRow, error)
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error)
	UpsertProduct(ctx context.Context, arg UpsertProductParams) error
	UpsertRestaurant(ctx context.Context, arg UpsertRestaurantParams) error
}

var _ Querier = (*Queries)(nil)
