// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurant_details.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getRestaurantWithProducts = `-- name: GetRestaurantWithProducts :many
SELECT
    r.restaurantID,
    r.restaurantName,
    r.category,
    r.address,
    r.parkingLot,
    p.id AS product_id,
    p.name AS product_name,
    p.description,
    p.price,
    p.is_available
FROM restaurants r
LEFT JOIN products p
ON p.restaurant_id = r.restaurantID
WHERE r.restaurantID = $1
`

type GetRestaurantWithProductsRow struct {
	Restaurantid   uuid.UUID      `json:"restaurantid"`
	Restaurantname string         `json:"restaurantname"`
	Category       string         `json:"category"`
	Address        string         `json:"address"`
	Parkinglot     bool           `json:"parkinglot"`
	ProductID      uuid.NullUUID  `json:"product_id"`
	ProductName    sql.NullString `json:"product_name"`
	Description    sql.NullString `json:"description"`
	Price          sql.NullString `json:"price"`
	IsAvailable    sql.NullBool   `json:"is_available"`
}

func (q *Queries) GetRestaurantWithProducts(ctx context.Context, restaurantid uuid.UUID) ([]GetRestaurantWithProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRestaurantWithProducts, restaurantid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRestaurantWithProductsRow
	for rows.Next() {
		var i GetRestaurantWithProductsRow
		if err := rows.Scan(
			&i.Restaurantid,
			&i.Restaurantname,
			&i.Category,
			&i.Address,
			&i.Parkinglot,
			&i.ProductID,
			&i.ProductName,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
