// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurants.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countRestaurants = `-- name: CountRestaurants :one
SELECT COUNT(*)
FROM restaurants
WHERE ($1::TEXT = '' OR restaurantName ILIKE '%' || $1 || '%')
  AND ($2::TEXT = '' OR category = $2)
`

type CountRestaurantsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountRestaurants(ctx context.Context, arg CountRestaurantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRestaurants, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRestaurant = `-- name: CreateRestaurant :exec
INSERT INTO restaurants (
    restaurantID,
    externalID,
    restaurantName,
    description,
    category,
    address,
    parkingLot,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (externalID) DO NOTHING
`

type CreateRestaurantParams struct {
	Restaurantid   uuid.UUID      `json:"restaurantid"`
	Externalid     int32          `json:"externalid"`
	Restaurantname string         `json:"restaurantname"`
	Description    sql.NullString `json:"description"`
	Category       string         `json:"category"`
	Address        string         `json:"address"`
	Parkinglot     bool           `json:"parkinglot"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, createRestaurant,
		arg.Restaurantid,
		arg.Externalid,
		arg.Restaurantname,
		arg.Description,
		arg.Category,
		arg.Address,
		arg.Parkinglot,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getRestaurantByExternalID = `-- name: GetRestaurantByExternalID :one
SELECT restaurantID, externalID, restaurantName, description, category, address, parkingLot, created_at, updated_at
FROM restaurants
WHERE externalID = $1
LIMIT 1
`

func (q *Queries) GetRestaurantByExternalID(ctx context.Context, externalid int32) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurantByExternalID, externalid)
	var i Restaurant
	err := row.Scan(
		&i.Restaurantid,
		&i.Externalid,
		&i.Restaurantname,
		&i.Description,
		&i.Category,
		&i.Address,
		&i.Parkinglot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurants = `-- name: GetRestaurants :many
SELECT restaurantID, restaurantName, address, category, parkingLot, created_at, updated_at
FROM restaurants
ORDER BY restaurantName
`

type GetRestaurantsRow struct {
	Restaurantid   uuid.UUID `json:"restaurantid"`
	Restaurantname string    `json:"restaurantname"`
	Address        string    `json:"address"`
	Category       string    `json:"category"`
	Parkinglot     bool      `json:"parkinglot"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetRestaurants(ctx context.Context) ([]GetRestaurantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRestaurants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRestaurantsRow
	for rows.Next() {
		var i GetRestaurantsRow
		if err := rows.Scan(
			&i.Restaurantid,
			&i.Restaurantname,
			&i.Address,
			&i.Category,
			&i.Parkinglot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT restaurantID, externalID, restaurantName, address, category, parkingLot, created_at
FROM restaurants
WHERE ($1::TEXT = '' OR restaurantName ILIKE '%' || $1 || '%')
  AND ($2::TEXT = '' OR category = $2)
ORDER BY restaurantName
LIMIT $3 OFFSET $4
`

type ListRestaurantsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListRestaurantsRow struct {
	Restaurantid   uuid.UUID `json:"restaurantid"`
	Externalid     int32     `json:"externalid"`
	Restaurantname string    `json:"restaurantname"`
	Address        string    `json:"address"`
	Category       string    `json:"category"`
	Parkinglot     bool      `json:"parkinglot"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListRestaurants(ctx context.Context, arg ListRestaurantsParams) ([]ListRestaurantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRestaurants,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestaurantsRow
	for rows.Next() {
		var i ListRestaurantsRow
		if err := rows.Scan(
			&i.Restaurantid,
			&i.Externalid,
			&i.Restaurantname,
			&i.Address,
			&i.Category,
			&i.Parkinglot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRestaurant = `-- name: UpsertRestaurant :exec
INSERT INTO restaurants (
    restaurantID,
    externalID,
    restaurantName,
    description,
    category,
    address,
    parkingLot,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (externalID) DO UPDATE SET
    restaurantName = EXCLUDED.restaurantName,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    address = EXCLUDED.address,
    parkingLot = EXCLUDED.parkingLot,
    updated_at = EXCLUDED.updated_at
`

type UpsertRestaurantParams struct {
	Restaurantid   uuid.UUID      `json:"restaurantid"`
	Externalid     int32          `json:"externalid"`
	Restaurantname string         `json:"restaurantname"`
	Description    sql.NullString `json:"description"`
	Category       string         `json:"category"`
	Address        string         `json:"address"`
	Parkinglot     bool           `json:"parkinglot"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertRestaurant(ctx context.Context, arg UpsertRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, upsertRestaurant,
		arg.Restaurantid,
		arg.Externalid,
		arg.Restaurantname,
		arg.Description,
		arg.Category,
		arg.Address,
		arg.Parkinglot,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
