// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: bitedash/v1/cart.proto

package bitedashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCartItemRequest) Reset() {
	*x = AddCartItemRequest{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCartItemRequest) ProtoMessage() {}

func (x *AddCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCartItemRequest.ProtoReflect.Descriptor instead.
func (*AddCartItemRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *AddCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddCartItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{1}
}

type RemoveCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartItemRequest) Reset() {
	*x = RemoveCartItemRequest{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartItemRequest) ProtoMessage() {}

func (x *RemoveCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveCartItemRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveCartItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{3}
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ClearCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartResponse) Reset() {
	*x = CartResponse{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartResponse) ProtoMessage() {}

func (x *CartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartResponse.ProtoReflect.Descriptor instead.
func (*CartResponse) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartResponse) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CartResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LineTotal     float64                `protobuf:"fixed64,5,opt,name=line_total,json=lineTotal,proto3" json:"line_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_bitedash_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetLineTotal() float64 {
	if x != nil {
		return x.LineTotal
	}
	return 0
}

var File_bitedash_v1_cart_proto protoreflect.FileDescriptor

const file_bitedash_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x16bitedash/v1/cart.proto\x12\vbitedash.v1\"O\n" +
	"\x12AddCartItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x10\n" +
	"\x0eGetCartRequest\"6\n" +
	"\x15RemoveCartItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x12\n" +
	"\x10ClearCartRequest\"-\n" +
	"\x11ClearCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\fCartResponse\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.bitedash.v1.CartItemR\x05items\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"\xa6\x01\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"line_total\x18\x05 \x01(\x01R\tlineTotal2\xb0\x02\n" +
	"\vCartService\x12E\n" +
	"\aAddItem\x12\x1f.bitedash.v1.AddCartItemRequest\x1a\x19.bitedash.v1.CartResponse\x12A\n" +
	"\aGetCart\x12\x1b.bitedash.v1.GetCartRequest\x1a\x19.bitedash.v1.CartResponse\x12K\n" +
	"\n" +
	"RemoveItem\x12\".bitedash.v1.RemoveCartItemRequest\x1a\x19.bitedash.v1.CartResponse\x12J\n" +
	"\tClearCart\x12\x1d.bitedash.v1.ClearCartRequest\x1a\x1e.bitedash.v1.ClearCartResponseB$Z\"internal/pb/bitedash/v1;bitedashv1b\x06proto3"

var (
	file_bitedash_v1_cart_proto_rawDescOnce sync.Once
	file_bitedash_v1_cart_proto_rawDescData []byte
)

func file_bitedash_v1_cart_proto_rawDescGZIP() []byte {
	file_bitedash_v1_cart_proto_rawDescOnce.Do(func() {
		file_bitedash_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bitedash_v1_cart_proto_rawDesc), len(file_bitedash_v1_cart_proto_rawDesc)))
	})
	return file_bitedash_v1_cart_proto_rawDescData
}

var file_bitedash_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bitedash_v1_cart_proto_goTypes = []any{
	(*AddCartItemRequest)(nil),    // 0: bitedash.v1.AddCartItemRequest
	(*GetCartRequest)(nil),        // 1: bitedash.v1.GetCartRequest
	(*RemoveCartItemRequest)(nil), // 2: bitedash.v1.RemoveCartItemRequest
	(*ClearCartRequest)(nil),      // 3: bitedash.v1.ClearCartRequest
	(*ClearCartResponse)(nil),     // 4: bitedash.v1.ClearCartResponse
	(*CartResponse)(nil),          // 5: bitedash.v1.CartResponse
	(*CartItem)(nil),              // 6: bitedash.v1.CartItem
}
var file_bitedash_v1_cart_proto_depIdxs = []int32{
	6, // 0: bitedash.v1.CartResponse.items:type_name -> bitedash.v1.CartItem
	0, // 1: bitedash.v1.CartService.AddItem:input_type -> bitedash.v1.AddCartItemRequest
	1, // 2: bitedash.v1.CartService.GetCart:input_type -> bitedash.v1.GetCartRequest
	2, // 3: bitedash.v1.CartService.RemoveItem:input_type -> bitedash.v1.RemoveCartItemRequest
	3, // 4: bitedash.v1.CartService.ClearCart:input_type -> bitedash.v1.ClearCartRequest
	5, // 5: bitedash.v1.CartService.AddItem:output_type -> bitedash.v1.CartResponse
	5, // 6: bitedash.v1.CartService.GetCart:output_type -> bitedash.v1.CartResponse
	5, // 7: bitedash.v1.CartService.RemoveItem:output_type -> bitedash.v1.CartResponse
	4, // 8: bitedash.v1.CartService.ClearCart:output_type -> bitedash.v1.ClearCartResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bitedash_v1_cart_proto_init() }
func file_bitedash_v1_cart_proto_init() {
	if File_bitedash_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bitedash_v1_cart_proto_rawDesc), len(file_bitedash_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bitedash_v1_cart_proto_goTypes,
		DependencyIndexes: file_bitedash_v1_cart_proto_depIdxs,
		MessageInfos:      file_bitedash_v1_cart_proto_msgTypes,
	}.Build()
	File_bitedash_v1_cart_proto = out.File
	file_bitedash_v1_cart_proto_goTypes = nil
	file_bitedash_v1_cart_proto_depIdxs = nil
}
