// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: bitedash/v1/restaurant.proto

package bitedashv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsRequest) Reset() {
	*x = ListRestaurantsRequest{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsRequest) ProtoMessage() {}

func (x *ListRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*ListRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *ListRestaurantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRestaurantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRestaurantsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListRestaurantsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsResponse) Reset() {
	*x = ListRestaurantsResponse{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsResponse) ProtoMessage() {}

func (x *ListRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*ListRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *ListRestaurantsResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *ListRestaurantsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRestaurantsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRestaurantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRestaurantByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantByIDRequest) Reset() {
	*x = GetRestaurantByIDRequest{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantByIDRequest) ProtoMessage() {}

func (x *GetRestaurantByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantByIDRequest) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *GetRestaurantByIDRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type GetRestaurantByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurant    *Restaurant            `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantByIDResponse) Reset() {
	*x = GetRestaurantByIDResponse{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantByIDResponse) ProtoMessage() {}

func (x *GetRestaurantByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantByIDResponse) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantByIDResponse) GetRestaurant() *Restaurant {
	if x != nil {
		return x.Restaurant
	}
	return nil
}

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    int32                  `protobuf:"varint,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	ParkingLot    bool                   `protobuf:"varint,7,opt,name=parking_lot,json=parkingLot,proto3" json:"parking_lot,omitempty"`
	Products      []*Product             `protobuf:"bytes,8,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Restaurant) GetExternalId() int32 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Restaurant) GetParkingLot() bool {
	if x != nil {
		return x.ParkingLot
	}
	return false
}

func (x *Restaurant) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId    int32                  `protobuf:"varint,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_bitedash_v1_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_bitedash_v1_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetExternalId() int32 {
	if x != nil {
		return x.ExternalId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_bitedash_v1_restaurant_proto protoreflect.FileDescriptor

const file_bitedash_v1_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x1cbitedash/v1/restaurant.proto\x12\vbitedash.v1\"v\n" +
	"\x16ListRestaurantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\x94\x01\n" +
	"\x17ListRestaurantsResponse\x129\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x17.bitedash.v1.RestaurantR\vrestaurants\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"?\n" +
	"\x18GetRestaurantByIDRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"T\n" +
	"\x19GetRestaurantByIDResponse\x127\n" +
	"\n" +
	"restaurant\x18\x01 \x01(\v2\x17.bitedash.v1.RestaurantR\n" +
	"restaurant\"\xfc\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\x05R\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x1f\n" +
	"\vparking_lot\x18\a \x01(\bR\n" +
	"parkingLot\x120\n" +
	"\bproducts\x18\b \x03(\v2\x14.bitedash.v1.ProductR\bproducts\"\xc6\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\x05R\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable2\xd5\x01\n" +
	"\x11RestaurantService\x12\\\n" +
	"\x0fListRestaurants\x12#.bitedash.v1.ListRestaurantsRequest\x1a$.bitedash.v1.ListRestaurantsResponse\x12b\n" +
	"\x11GetRestaurantByID\x12%.bitedash.v1.GetRestaurantByIDRequest\x1a&.bitedash.v1.GetRestaurantByIDResponseB$Z\"internal/pb/bitedash/v1;bitedashv1b\x06proto3"

var (
	file_bitedash_v1_restaurant_proto_rawDescOnce sync.Once
	file_bitedash_v1_restaurant_proto_rawDescData []byte
)

func file_bitedash_v1_restaurant_proto_rawDescGZIP() []byte {
	file_bitedash_v1_restaurant_proto_rawDescOnce.Do(func() {
		file_bitedash_v1_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bitedash_v1_restaurant_proto_rawDesc), len(file_bitedash_v1_restaurant_proto_rawDesc)))
	})
	return file_bitedash_v1_restaurant_proto_rawDescData
}

var file_bitedash_v1_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bitedash_v1_restaurant_proto_goTypes = []any{
	(*ListRestaurantsRequest)(nil),    // 0: bitedash.v1.ListRestaurantsRequest
	(*ListRestaurantsResponse)(nil),   // 1: bitedash.v1.ListRestaurantsResponse
	(*GetRestaurantByIDRequest)(nil),  // 2: bitedash.v1.GetRestaurantByIDRequest
	(*GetRestaurantByIDResponse)(nil), // 3: bitedash.v1.GetRestaurantByIDResponse
	(*Restaurant)(nil),                // 4: bitedash.v1.Restaurant
	(*Product)(nil),                   // 5: bitedash.v1.Product
}
var file_bitedash_v1_restaurant_proto_depIdxs = []int32{
	4, // 0: bitedash.v1.ListRestaurantsResponse.restaurants:type_name -> bitedash.v1.Restaurant
	4, // 1: bitedash.v1.GetRestaurantByIDResponse.restaurant:type_name -> bitedash.v1.Restaurant
	5, // 2: bitedash.v1.Restaurant.products:type_name -> bitedash.v1.Product
	0, // 3: bitedash.v1.RestaurantService.ListRestaurants:input_type -> bitedash.v1.ListRestaurantsRequest
	2, // 4: bitedash.v1.RestaurantService.GetRestaurantByID:input_type -> bitedash.v1.GetRestaurantByIDRequest
	1, // 5: bitedash.v1.RestaurantService.ListRestaurants:output_type -> bitedash.v1.ListRestaurantsResponse
	3, // 6: bitedash.v1.RestaurantService.GetRestaurantByID:output_type -> bitedash.v1.GetRestaurantByIDResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bitedash_v1_restaurant_proto_init() }
func file_bitedash_v1_restaurant_proto_init() {
	if File_bitedash_v1_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bitedash_v1_restaurant_proto_rawDesc), len(file_bitedash_v1_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bitedash_v1_restaurant_proto_goTypes,
		DependencyIndexes: file_bitedash_v1_restaurant_proto_depIdxs,
		MessageInfos:      file_bitedash_v1_restaurant_proto_msgTypes,
	}.Build()
	File_bitedash_v1_restaurant_proto = out.File
	file_bitedash_v1_restaurant_proto_goTypes = nil
	file_bitedash_v1_restaurant_proto_depIdxs = nil
}
